version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Run tests"
          npm run test

  deploy:
    docker:
      - image:  cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a faizal-su-devops
            heroku container:push web -a faizal-su-devops
            heroku container:release web -a faizal-su-devops

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps: 
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Hub Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            
      - run:
          name: Build Docker Image
          command: docker build -t education-space/6m-software-m4-node-app-for-devops .
      - run:
          name: Tag Docker Image
          command:  docker tag education-space/6m-software-m4-node-app-for-devops:1.0.0
      - run:
          name: Push Odcker Image
          command:  docker push education-space/6m-software-m4-node-app-for-devops:1.0.0

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          images: faizal/education-space
      - docker/push:  
          images: faizal/education-space

  scan:
    docker:
      - image:  cimg/node:16.10
    environment:
      IMAGE_NAME: faizal/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run:  docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name:  $IMAGE_NAME
  codescan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: faizal/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - snyk/install
      - run: |
          snyk code test

workflows:
  simple_workflow:
    jobs:
      - build
          # - deploy:
          #     requires:
          #       - test
      - scan:
          requires:
            - build
      - codescan:
          requires:
            - build
      - test:
          requires:
            - scan
      # - build-and-push:
      #     requires:
      #       - test
