version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          echo "Run tests"
          npm run test

  deploy:
    docker:
      - image:  cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a faizal-su-devops
            heroku container:push web -a faizal-su-devops
            heroku container:release web -a faizal-su-devops

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps: 
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "!Laziafhakim9ii7" | docker login -u "faizalhh17" --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t education-space/6m-software-m4-node-app-for-devops .
      - run:
          name: Tag Docker Image
          command:  docker tag education-space/6m-software-m4-node-app-for-devops:1.0.0
      - run:
          name: Push Odcker Image
          command:  docker push education-space/6m-software-m4-node-app-for-devops:1.0.0

  publish:
    executor: docker/docker
    steps:
      - csetup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          images: faizal/education-space
      - docker/push:  
          images: faizal/education-space

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - test