version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/isntall-packages:
          pkg-manager: npm
      - run:
          echo "Run tests"
          npm run test

  build-and-push:
    docker:
      - images: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command:  |
            docker build -t education-space/6m-software-m4-node-app-for-devops:${CIRCLE_SHA1} .
      - run:
          name: Login to Docker Image
          command:  |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command:  |
            docker push education-space/6m-software-m4-node-app-for-devops:${CIRCLE_SHA1}


  deploy:
    docker:
      - image:  cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a faizal-su-devops
            heroku container:push web -a faizal-su-devops
            heroku container:release web -a faizal-su-devops


workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build